name = input("Enter your name: ")
age = int(input("Enter your age: "))
year= int(input("Enter current year: "))
futureYear=int(input("Enter future year: "))
futureAge=age+(futureYear-year)
print(name+" will be",futureAge,"in",futureYear)